version: '3'
services:
  mjai-server:
    build: ./
    ports:
      - 11600:11600
  rb-server:
    image: python:3.6-alpine
    volumes:
      - ./src:/src
    ports:
      - 11601:11601
    command: python /src/replay_buffer.py
  mjai-client1:
    image: python:3.6-alpine
    volumes:
      - ./src:/src
    links:
      - mjai-server
      - rb-server
    command: python /src/selfplay_client.py tcp://mjai-server:11600 tcp://rb-server:11601
  mjai-client2:
      image: python:3.6-alpine
      volumes:
        - ./src:/src
      links:
        - mjai-server
        - rb-server
      command: python /src/selfplay_client.py tcp://mjai-server:11600 tcp://rb-server:11601
  mjai-client3:
      image: python:3.6-alpine
      volumes:
        - ./src:/src
      links:
        - mjai-server
        - rb-server
      command: python /src/selfplay_client.py tcp://mjai-server:11600 tcp://rb-server:11601
  mjai-client4:
      image: python:3.6-alpine
      volumes:
        - ./src:/src
      links:
        - mjai-server
        - rb-server
      command: python /src/selfplay_client.py tcp://mjai-server:11600 tcp://rb-server:11601
